- name: copy file
  copy: src=stress-1.0.4.tar.gz dest=/tmp/stress-1.0.4.tar.gz mode=0777

- name: tar file
  shell: cd /tmp && tar xvf stress-1.0.4.tar.gz && rm -rf stress-1.0.4.tar.gz

- name: run install stress
  shell: cd /tmp/stress-1.0.4 && ./configure && make && make install
  become: true
  become_method: sudo
  become_user: root
  ignore_errors: yes

- name: copy stress-ng.zip file
  copy: src=stress-ng.zip dest=/tmp/stress-ng.zip mode=0777

- name: tar file
  shell: cd /tmp && unzip stress-ng.zip && rm -rf stress-ng.zip

- name: run install stress
  shell: cd /tmp/stress-ng-master && make && make install
  become: true
  become_method: sudo
  become_user: root
  ignore_errors: yes



